/*
 * This file is generated by jOOQ.
 */
package ru.mai.lessons.rpks.jooq.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ru.mai.lessons.rpks.jooq.model.tables.EnrichmentRules;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnrichmentRulesRecord extends UpdatableRecordImpl<EnrichmentRulesRecord> implements Record7<Integer, Long, Long, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.enrichment_rules.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.enrichment_rules.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.enrichment_rules.enrichment_id</code>.
     */
    public void setEnrichmentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.enrichment_rules.enrichment_id</code>.
     */
    public Long getEnrichmentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.enrichment_rules.rule_id</code>.
     */
    public void setRuleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.enrichment_rules.rule_id</code>.
     */
    public Long getRuleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.enrichment_rules.field_name</code>.
     */
    public void setFieldName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.enrichment_rules.field_name</code>.
     */
    public String getFieldName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.enrichment_rules.field_name_enrichment</code>.
     */
    public void setFieldNameEnrichment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.enrichment_rules.field_name_enrichment</code>.
     */
    public String getFieldNameEnrichment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.enrichment_rules.field_value</code>.
     */
    public void setFieldValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.enrichment_rules.field_value</code>.
     */
    public String getFieldValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.enrichment_rules.field_value_default</code>.
     */
    public void setFieldValueDefault(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.enrichment_rules.field_value_default</code>.
     */
    public String getFieldValueDefault() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Long, Long, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Long, Long, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return EnrichmentRules.ENRICHMENT_RULES.ID;
    }

    @Override
    public Field<Long> field2() {
        return EnrichmentRules.ENRICHMENT_RULES.ENRICHMENT_ID;
    }

    @Override
    public Field<Long> field3() {
        return EnrichmentRules.ENRICHMENT_RULES.RULE_ID;
    }

    @Override
    public Field<String> field4() {
        return EnrichmentRules.ENRICHMENT_RULES.FIELD_NAME;
    }

    @Override
    public Field<String> field5() {
        return EnrichmentRules.ENRICHMENT_RULES.FIELD_NAME_ENRICHMENT;
    }

    @Override
    public Field<String> field6() {
        return EnrichmentRules.ENRICHMENT_RULES.FIELD_VALUE;
    }

    @Override
    public Field<String> field7() {
        return EnrichmentRules.ENRICHMENT_RULES.FIELD_VALUE_DEFAULT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getEnrichmentId();
    }

    @Override
    public Long component3() {
        return getRuleId();
    }

    @Override
    public String component4() {
        return getFieldName();
    }

    @Override
    public String component5() {
        return getFieldNameEnrichment();
    }

    @Override
    public String component6() {
        return getFieldValue();
    }

    @Override
    public String component7() {
        return getFieldValueDefault();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getEnrichmentId();
    }

    @Override
    public Long value3() {
        return getRuleId();
    }

    @Override
    public String value4() {
        return getFieldName();
    }

    @Override
    public String value5() {
        return getFieldNameEnrichment();
    }

    @Override
    public String value6() {
        return getFieldValue();
    }

    @Override
    public String value7() {
        return getFieldValueDefault();
    }

    @Override
    public EnrichmentRulesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EnrichmentRulesRecord value2(Long value) {
        setEnrichmentId(value);
        return this;
    }

    @Override
    public EnrichmentRulesRecord value3(Long value) {
        setRuleId(value);
        return this;
    }

    @Override
    public EnrichmentRulesRecord value4(String value) {
        setFieldName(value);
        return this;
    }

    @Override
    public EnrichmentRulesRecord value5(String value) {
        setFieldNameEnrichment(value);
        return this;
    }

    @Override
    public EnrichmentRulesRecord value6(String value) {
        setFieldValue(value);
        return this;
    }

    @Override
    public EnrichmentRulesRecord value7(String value) {
        setFieldValueDefault(value);
        return this;
    }

    @Override
    public EnrichmentRulesRecord values(Integer value1, Long value2, Long value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnrichmentRulesRecord
     */
    public EnrichmentRulesRecord() {
        super(EnrichmentRules.ENRICHMENT_RULES);
    }

    /**
     * Create a detached, initialised EnrichmentRulesRecord
     */
    public EnrichmentRulesRecord(Integer id, Long enrichmentId, Long ruleId, String fieldName, String fieldNameEnrichment, String fieldValue, String fieldValueDefault) {
        super(EnrichmentRules.ENRICHMENT_RULES);

        setId(id);
        setEnrichmentId(enrichmentId);
        setRuleId(ruleId);
        setFieldName(fieldName);
        setFieldNameEnrichment(fieldNameEnrichment);
        setFieldValue(fieldValue);
        setFieldValueDefault(fieldValueDefault);
    }
}