/*
 * This file is generated by jOOQ.
 */
package ru.mai.lessons.rpks.jooq.model;


import ru.mai.lessons.rpks.jooq.model.tables.EnrichmentRules;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.enrichment_rules</code>.
     */
    public static final EnrichmentRules ENRICHMENT_RULES = EnrichmentRules.ENRICHMENT_RULES;
}